[package]
name = "led-matrix-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
led-matrix-core = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
