[package]
name = "zhaw-led-matrix-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.2"
zhaw-led-matrix-core = { version = "0.1.0", path = "../zhaw-led-matrix-core" }
